name: time_left
description: A life expectancy calculator app.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# In Windows, build-name is used as the major, minor, and patch parts
# of the product's version while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  animated_check: ^1.0.5
  animated_text_kit: ^4.2.2
  bot_toast: ^4.1.3
  cached_network_image: ^3.3.1
  card_swiper: ^3.0.1
  carousel_slider: ^5.0.0
  csv: ^6.0.0
  cupertino_icons: ^1.0.2
  data_table_2: ^2.5.12
  date_picker_plus: ^4.0.0
  desktop_window: ^0.4.0
  dotted_border: ^2.1.0
  eva_icons_flutter: ^3.1.0
  file_picker: ^8.1.2
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  fpdart: ^1.1.0
  get_it: ^7.6.7
  hive: ^4.0.0-dev.2
  iconly: ^1.0.1
  image_picker: ^1.0.7
  internet_connection_checker_plus: ^2.4.0
  intl: ^0.19.0
  isar_flutter_libs: ^4.0.0-dev.13
  logger: ^2.3.0
  lottie: ^3.1.2
  mock_supabase_http_client: ^0.0.2
  path_provider: ^2.1.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  supabase_flutter: ^2.3.4
  tab_container: ^3.5.3
  table_calendar: ^3.1.2
  timeline_tile: ^2.0.0
  timezone: ^0.9.4
  uuid: ^4.3.3
  visibility_detector: ^0.4.0+2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  syncfusion_flutter_xlsio: ^24.1.41
  http: ^1.1.0
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - .env
